### ISSUE TITLE
404 Error for Installation of Nextcloud instance

### ISSUE THREAD

**Issue by thomasok04** [LukeSmithxyz/landchad#101]
G'day everyone, I've been following all of Luke's tutorials and everything has been working great :), that is until i follow the nextcloud tutorial and end up with a 404 error when i try accessing the control panel after following all the installation steps. Any tips?

**Comment by new-on-github32702** [comment]
See the Issue I created. The long code block that is supposed to go into /etc/nginx/sites-available/nextcloud references different locations for our SSL-certificates. So it doesnt't line up with the tutorial we did before. Use `journalct -xe` to check yourself. (For me I already get an Error when I do `systemctl reload nginx`)

**Comment by thomasok04** [comment]
> See the Issue I created. The long code block that is supposed to go into /etc/nginx/sites-available/nextcloud references different locations for our SSL-certificates. So it doesnt't line up with the tutorial we did before. Use `journalct -xe` to check yourself. (For me I already get an Error when I do `systemctl reload nginx`)


Cheers for the response, fortunately I recognized that difference so I fixed it when adding the code in. Mine looks like this

`ssl_certificate     /etc/letsencrypt/live/----.xyz/cert.pem;
 ssl_certificate_key /etc/letsencrypt/live/----.xyz/privkey.pem;`
Is this what it should look like?
(---- takes the place of my website name for privacy reasons)

**Comment by thomasok04** [comment]
luke don’t close my issue 😭😭😭

**Comment by thomasok04** [comment]
update, when i try and remedy the root path in my config, and then go to the website, the file `index.php` is downloaded. very weird

**Comment by jotoho** [comment]
@thomasok04 I think the downloading of php files of displaying it could be a symptom of php not being installed/configured correctly.
