### ISSUE TITLE
Email tutorial

### ISSUE THREAD

**Issue by theonelucas** [LukeSmithxyz/landchad#105]
Is anyone working on the email tutorial? Since the site launched it says in the homepage that it's been in the workings, but I didn't find any PR related to that.

**Comment by LukeSmithxyz** [comment]
If you want, you can write an article on any of these topics, as I am not actively working on it now.

**Comment by CyberTailor** [comment]
I'd recommend this tutorial (OpenSMTPD, Dovecot, rspamd)
https://prefetch.eu/blog/2020/email-server/

**Comment by krisdoodle45** [comment]
For the first one, #19

**Comment by storopoli** [comment]
This would be really great. We have already advanced tutorials on XMPP, Calibre, Matrix etc.
A back to basics your own email server would be great.

**Comment by LukeSmithxyz** [comment]
Closing this for now. Note that there are some drafts in `content/email` that I will slowly be building out as I have interest. If interested parties want to contribute to push it to release, that's welcome.
