### ISSUE TITLE
Epik recomendation is controversial

### ISSUE THREAD

**Issue by CyberTailor** [LukeSmithxyz/landchad#106]
They are literally (in)famous only for providing services to the Nazis.
https://en.wikipedia.org/wiki/Epik_(company)

I find [OpenNIC](https://www.opennic.org/) domains the most based but only those who use opennic DNS servers can access them.

It seems like lots of FOSS projects/organizations use this:
https://en.wikipedia.org/wiki/Gandi

Personally I just stick to whatever is cheapest to renewal
https://tld-list.com/

***

by the way, it is a sarcasm? if it is, i find it very funny :)
> use a registrar based in Russia or China or a country more sympathetic to political criticism

**Comment by termermc** [comment]
If they're unlikely to take down your site for nonsense reasons then who really cares? If they have a history of taking down random peoples' domains for political or content reasons then maybe it would matter, but I don't know anything about that for Epik. I can't see a reason to care who they do business with if they also do business with you and are cheap. Although I don't know about their prices, maybe they're expensive.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by owwk** [comment]
ты никогда не будешь настоящей женщиной

**Comment by LukeSmithxyz** [comment]
This is precisely why Epik is one of the only large-scale registrars worth using.

What goes on in these people's empty heads? "Controversial" that Epik doesn't ban people? If that's what you want, you should be using curated social engineering sites Facebook or Google to communicate.

Granted Epik isn't perfect. There are some sites they have banned for semi-political reasons after financial pressure from other oragnizations, but Epik is the registrar with the best reputation among those that have a normie-friendly UI.
