### ISSUE TITLE
Mirror Your Site Over Tor: no hostname file

### ISSUE THREAD

**Issue by spaceneb** [LukeSmithxyz/landchad#116]
I tried mirror my site over tor, following the guide. After editing the config and reloading, the hostname file doesn't get loaded.

```
root@myserver:~#  cat /var/lib/tor/hidden_service/hostname
cat: /var/lib/tor/hidden_service/hostname: No such file or directory
```

uname -a
```
Linux [[hostname]] 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
```

**Comment by danielfan61a** [comment]
just `systemctl restart tor` and it should work. note: you can have a vanity url using [mkp224o](https://github.com/cathugger/mkp224o).
