### ISSUE TITLE
Using fail2ban as a more advanced firewall

### ISSUE THREAD

**Issue by spaceneb** [LukeSmithxyz/landchad#117]
fail2ban is great but a pain in the ass to get setup. A guide on how to set it up for email and other services would be great.

**Comment by termermc** [comment]
If it wasn't covered in the setup tutorial, SSH security with it should be mentioned

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielfan61a** [comment]
https://linuxize.com/post/install-configure-fail2ban-on-ubuntu-20-04/
