### ISSUE TITLE
LandChad's Web button

### ISSUE THREAD

**Issue by tfasano1** [LukeSmithxyz/landchad#120]
Not sure if there is a size cap (this one's ~15kb) but here's mine:
![landchad](https://user-images.githubusercontent.com/54379134/130359133-6c81d1bf-f1b2-4231-8f75-cdb8a822daf5.gif)

Maybe other's can post their own web buttons for landchad.net so we can compare them all in one place, or so other's can be inspired to make a better one.

**Comment by LukeSmithxyz** [comment]
Looks nice!

Do you have the source file for it? I might be able to minimize the
size.

**Comment by termermc** [comment]
LOL badass

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tfasano1** [comment]
[landchad.zip](https://github.com/LukeSmithxyz/landchad/files/7027791/landchad.zip)
