### ISSUE TITLE
can't restart Nginx after following Nextcloud guide

### ISSUE THREAD

**Issue by themaster567** [LukeSmithxyz/landchad#121]
This is the error I get.

```
nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/example.org/cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/example.org/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
I'm not sure what to do. issue #89 has the exact same problem here with no resolution. I can confirm that SSL works just fine, as I had https working perfectly with the blog portion of my site. It was only after following the Nextcloud guide and attempting to restart Nginx that it's giving me this problem. I can't have simultaneously used Certbot incorrectly and correctly at the same time.

**Comment by LukeSmithxyz** [comment]
Change the highlighted content of the configuration file in the tutorial to match the location of your SSL cert.

**Comment by themaster567** [comment]
> Change the highlighted content of the configuration file in the tutorial to match the location of your SSL cert.

I'm a moron. It literally says "example.org" RIGHT IN THE OUTPUT!
