### ISSUE TITLE
new guide submission: matrix homeserver / synapse

### ISSUE THREAD

**Issue by dreamerchris** [LukeSmithxyz/landchad#130]
I could write a matrix-synapse guide but i see you have it under construction. Should you give me green light I will write the guide!

**Comment by leopoldfajtak** [comment]
I found that [this guide](https://www.natrius.eu/dokuwiki/doku.php?id=digital:server:matrixsynapse) would fit well to landchad.net after some small adaptations.
Things to change would be:
+ Skip Step 4
+ Adapt Step 5 to change /etc/nginx/sites-availible/mywebsite (there's not much to do)
+ Skip Step 7
