### ISSUE TITLE
RSS Feed Application suggestion (single PWA that adopts the Unix/Libre software philosophy)

### ISSUE THREAD

**Issue by SahidMiller** [LukeSmithxyz/landchad#133]
This mysteriously disappeared from YouTube comments section so I'm sharing here in case you're interested. This seemed like the best repository to create the issue.

My main motivation with this suggestion is to help developers avoid managing a specific website, server, or offline webapp for something as simple as RSS. That's crazy inefficient imo.

- Developers clearly want to focus on building apps that does one thing and one thing alone and not worry about where it's hosted. 
- And users/normies clearly just want to **run** these apps in the browser without any desktop/server installation.

My suggestion is a single PWA that adopts Unix/Libre software philosophy (MVP) :
- uses xterm.js for bare minimum but *extensible* UI
- uses IPFS/IndexedDB for a filesystem so *everything on the web is a content addressable file.*
- uses libp2p for networking and getting around CORS without compromising security or configurability (via tunnels not proxies)

As long as everything is shimmed correctly, this should make it **possible for users to run any existing CLI or webapp** in the browser with something as simple as `yarn install <dope-rss-package>`

**Comment by termermc** [comment]
Are you just suggesting a web container for NodeJS applications lol

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by SahidMiller** [comment]
> Are you just suggesting a web container for NodeJS applications lol

That sounds like you're amused reading a suggestion to build a web container for an RSS application? If that's the case, that's very understandable lol and I'm sorry I wasn't clear. I'd like to clarify if you don't mind! 

I'm suggesting to develop a regular ol' Nodejs RSS app (using express, hapi, etc. or just CLI...) but without necessarily hosting it as a site or app yourself. 

The web container is just an technical explanation of what needs to exist for that to be a reasonable idea, God willing... But apologies if that's way off mark for landchad!

**Comment by termermc** [comment]
I'm just not understanding the application of this, for RSS or otherwise. Or what this really is, for that matter.

**Comment by SahidMiller** [comment]
So a user can do this in a single PWA with a terminal as the basic UI component:

`yarn global add <cool-rss-app>` <- use libp2p to fetch and ipfs to store locally in indexeddb

`node cool-rss-app` <- run the app in a worker with appropriate shims (like http(s))

`open /cool-rss-app` <- see the result, using service workers.

Or they can self host by using SSH instead to do pretty much the same thing on a linux box

**Comment by termermc** [comment]
So yeah, basically a NodeJS container in the browser
