### ISSUE TITLE
Mention different php version in Debian11 for rss-bridge tutorial

### ISSUE THREAD

**Issue by leopoldfajtak** [LukeSmithxyz/landchad#134]
The rss-bridge tutorial works for Debian 11 (where php7.3 has been replaced by php7.4) after replacing all occurrences of php7.3 with php7.4 (this is in the `apt` command and in the file `/etc/nginx/sites-available/rss-bridge`.

I understand that current policy states that tutorials have to be written for Debian10, but mentioning this could save some tinkering time for lots of people.

**Comment by LukeSmithxyz** [comment]
Yeah, I mean to update everything to Debian 11 too. I'll have a commit with the changes pretty soon.
