### ISSUE TITLE
www. doesn't work? 

### ISSUE THREAD

**Issue by inezserrano** [LukeSmithxyz/landchad#139]
I followed the guide completely, mysite.com works, but www.mysite.com still goes to the default nginx page.

**Comment by inezserrano** [comment]
The only issue is with certbot I think? The page works but it isn't secure.

**Comment by termermc** [comment]
Make sure your www. domain is getting renewed along with the normal domain's certificate. Remember, www is not special, it's just like any other subdomain, so it needs to be included in the subjects of a certificate, or have its own certificate.
