### ISSUE TITLE
Suggestion: Learning with Text

### ISSUE THREAD

**Issue by chrisbohn8** [LukeSmithxyz/landchad#140]
Learning with Text (LWT) is a FOSS language learning tool. Donovan (iBSD / Messofanti Guild) has done some videos on it which showcase it https://youtu.be/fYV3EB868Mk

All of the official documentation uses an Apache server, but I imagine using an nginx server would be possible.

**Comment by LukeSmithxyz** [comment]
I don't know too much about it. I'm welcome to an article submission though if it's FLOSS and useful enough.
