### ISSUE TITLE
Suggestion, file sharing modules in prosody.

### ISSUE THREAD

**Issue by el3ctr0lyte** [LukeSmithxyz/landchad#145]
Maybe we could modify the prosody guide to enable http_file(for downloading files) and http_upload(for uploading files) modules. I think it would make it a bit more normie friendly because most IM's allow you to share files.

**Comment by LukeSmithxyz** [comment]
Sounds like a good idea.

**Comment by el3ctr0lyte** [comment]
I am going to try and write it up later this week or maybe this weekend. But if anyone else wants to write it up, [here](https://homebrewserver.club/configuring-a-modern-xmpp-server.html) is a good guide that shows how to do this. It is litterally just adding a `Component "uploads.example.com" "http_upload"` and a few options like max upload size. [Here](https://modules.prosody.im/mod_http_upload) is the documentation for the module. Please note that they say specifically to NOT ADD IT under modules_enabled. Just add the component!

**Comment by el3ctr0lyte** [comment]
Also [here](https://homebrewserver.club/server-support-for-audio-video-calls.html) is a guide from the same website that shows how to setup prosody for audio/video calling. It is just setting up a turn server(for which we already have a guide) and configuring the options in the prosody config.
