### ISSUE TITLE
MkDocs article (markdown SSG)

### ISSUE THREAD

**Issue by wlwww16** [LukeSmithxyz/landchad#148]
MkDocs is a static site generator which uses markdown files to generate static HTML/CSS with support for themes and plugins. You can view the site [here](https://www.mkdocs.org/)

I used it many years ago, and found it to be helpful. Is this the sort of thing the "community" would be interested in a tutorial for? If so, I could probably write it, I just don't want to commit to writing the tutorial if the general consensus is that it's bloat cringe soydev 100 free punjabi no virus.

**Comment by slashformotion** [comment]
I use it because it's really lite and very easy to setup

**Comment by LukeSmithxyz** [comment]
I'm open to it if someone wants to write it. I don't know it myself.

Reminds me I might want to put back up the calls for new articles on the landchad.net mainpage.
