### ISSUE TITLE
WIP: Suggestions: DNS, VPN, etc.

### ISSUE THREAD

**Issue by ElectricGeorge** [LukeSmithxyz/landchad#15]
I have a few suggestions for topics that aren't listed yet

* **(Pull Request)** BIND9 authoritative nameserver with DNSSEC
* **(WIP)** DNS resolver with DNS-over-TLS and DNS-over-HTTPS
* OpenLDAP server
* Kerberos 5 authentication
* Fail2ban w/ endlessh tarpit (maybe part of firewall article)
* OpenVPN or IPsec

I may be able to write articles for a few of them as I am currently using them on my server. Some of these are needlessly difficult to set up because of the lack of good tutorials and I think people would have good uses for them (Fine-grained control over dns, auth across services, etc.). Would tutorials for any of these services be considered?

**Comment by LukeSmithxyz** [comment]
All of those sound like great ideas.

**Comment by Juliaria08** [comment]
> I have a few suggestions for topics that aren't listed yet
> 
> * **(WIP)** BIND9 authoritative nameserver with DNSSEC
> * **(WIP)** DNS resolver with DNS-over-TLS and DNS-over-HTTPS
> * OpenLDAP server
> * Kerberos 5 authentication
> * Fail2ban w/ endlessh tarpit (maybe part of firewall article)
> * OpenVPN or IPsec
> 
> I may be able to write articles for a few of them as I am currently using them on my server. Some of these are needlessly difficult to set up because of the lack of good tutorials and I think people would have good uses for them (Fine-grained control over dns, auth across services, etc.). Would tutorials for any of these services be considered?

About Kerberos i want to try it out, thanks for helping. I am going to try to make a irc article myself

**Comment by ElectricGeorge** [comment]
Alright, I'll hold off on OpenLDAP until Kerberos is done. I want to have Kerberos as a SASL backend to OpenLDAP

**Comment by phirecc** [comment]
I think WireGuard would be better than OpenVPN/IPsec, since it's easier and better on so many levels. I could write a post about it if nobody else wants to, however posts on IPs, subnets, interfaces, routing and such would be good as prerequesites

**Comment by ElectricGeorge** [comment]
I haven't really looked into WireGuard, but sure, go ahead. A post about basic networking sounds like a good idea too. I listed IPsec because it is standardized by the IETF and I have used it in the past

**Comment by Juliaria08** [comment]
> I have a few suggestions for topics that aren't listed yet
> 
> * **(Pull Request)** BIND9 authoritative nameserver with DNSSEC
> * **(WIP)** DNS resolver with DNS-over-TLS and DNS-over-HTTPS
> * OpenLDAP server
> * **(WIP @Juliaria08)** Kerberos 5 authentication
> * Fail2ban w/ endlessh tarpit (maybe part of firewall article)
> * OpenVPN or IPsec
> 
> I may be able to write articles for a few of them as I am currently using them on my server. Some of these are needlessly difficult to set up because of the lack of good tutorials and I think people would have good uses for them (Fine-grained control over dns, auth across services, etc.). Would tutorials for any of these services be considered?

@ElectricGeorge No i dont know how to do kerberos. I want to try it out when the article releases

**Comment by ElectricGeorge** [comment]
@Juliaria08 Oh, sorry about that lol. Totally misunderstood

**Comment by WitherCubes** [comment]
I may also submit a tutorial very soon on setting up Pihole with blocklists.
