### ISSUE TITLE
Release under libre license

### ISSUE THREAD

**Issue by throwaway1037** [LukeSmithxyz/landchad#153]
Until the project is officially placed under a libre license, it is proprietary.

See https://freedomdefined.org for the definition of libre works and some libre licenses.

**Comment by climbTheStairs** [comment]
Since this is not a software program, one of the Creative Commons licenses would be nice for this.  I'd recommend CC0 (if Luke wants to release to the public domain) or CC-BY; or if copyleft is preferred, CC-BY-SA or GFDL would also work.

**Comment by throwaway1037** [comment]
@climbTheStairs
> one of the Creative Commons licenses would be nice for this

As long as it's one of the free ones :)

I'd recommend a strong copleft license such as CC-BY-SA-4.0-Int-or-later.

**Comment by SergioFLS** [comment]
one problem that i can think of is on getting all contributors to agree to license their contributions under a license that's compatible with each other licenses...

**Comment by throwaway1037** [comment]
The real issue is liberating existing contributions.
As the site is an aggregation of articles, the licenses don't have to be compatible, just libre.
