### ISSUE TITLE
Instructions for enabling Tor with systemd do not work

### ISSUE THREAD

**Issue by climbTheStairs** [LukeSmithxyz/landchad#155]
Right now, [tor.html](https://landchad.net/tor) recommends enabling the systemd Tor service:

```
systemctl enable --now tor
```

However, this does not seem to work, at least not for me on my Debian server because the default file [`tor.service`](https://gitweb.torproject.org/debian/tor.git/tree/debian/systemd/tor.service) does absolutely nothing.

This is because Debian supports multiple Tor instance, and a new one must be created:

```
# Create instance
tor-instance-create MY_INSTANCE_NAME
# Edit `torrc`
# (Set `HiddenServiceDir` to be inside `/var/lib/tor-instances/MY_INSTANCE_NAME`)
vi /etc/tor/instances/MY_INSTANCE_NAME/torrc
# Start systemd service
systemctl enable --now tor@MY_INSTANCE_NAME
```

There also comes a default Tor instance (`tor@default.service`) but for some reason systemd doesn't let it be `enable`d.

See https://askubuntu.com/a/903341 and `man tor-instance-create`.

**Comment by tfasano1** [comment]
You already made a pull request, just add these findings to it. I did a fresh install of tor following the guide 20 minutes ago on a Debian 10 VPS (amd64). Everything worked until printing out the hostname. That's an easy fix though, just do `systemctl restart tor`. 

If there is some radically different way of setting tor up with systemd I'm not opposed to it, but the tutorial should be rewritten.

**Comment by climbTheStairs** [comment]
If everything works for you, then that would mean that the setup varies across different system, so I'm not sure what to put.

On my Debian 11 (bullseye) x86_64 server, my `tor.service` file does not start Tor and there are two other service files for Tor.

```
cat /lib/systemd/system/tor.service
----
# This service is actually a systemd target,
# but we are using a service since targets cannot be reloaded.

[Unit]
Description=Anonymizing overlay network for TCP (multi-instance-master)

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/true
ExecReload=/bin/true

[Install]
WantedBy=multi-user.target
```

```
ls /lib/systemd/system/tor*.service
----
/lib/systemd/system/tor.service
/lib/systemd/system/tor@.service
/lib/systemd/system/tor@default.service
```

What happens when you run `cat /lib/systemd/system/tor.service` and `ls /lib/systemd/system/tor*.service`?

**Comment by tfasano1** [comment]
The outputs are identical. If you do figure out a Debian 11 solution (most likely a systemd problem) then post your solution here.

**Comment by climbTheStairs** [comment]
Strangely, it's working now.  It seems that `tor.service` starts `tor@default.service`, which loads the normal config file at `/etc/torrc`.  Thanks for the help.
