### ISSUE TITLE
Matrix: Fails to start if IPv6 is not bind-able

### ISSUE THREAD

**Issue by josephbburg** [LukeSmithxyz/landchad#163]
Hello,
I followed the instructions on Landchad and Matrix wouldn't start. I found a solution to the problem here: https://stackoverflow.com/questions/56164787/couldnt-listen-on-8008-errno-97-address-family-not-supported-by-protocol
It would be nice to add a little memo warning people of this.

**Comment by LukeSmithxyz** [comment]
All the article here assume we use both IPv4 and IPv6 and this is how the introductory tutorials set things up.
