### ISSUE TITLE
Calibre tutorial certbot might not work

### ISSUE THREAD

**Issue by Dragallur** [LukeSmithxyz/landchad#171]
I had everything set up as the basic tutorial said. I tried to create calibre-server but the certification didn'ŧ work. When I ran 
`certbot --nginx ` I didn'ŧ get the option to add calibre.myserver.xxx. User might be tempted to add it manually with `certbot --nginx -d calibre.myserver.xxx` but this adds the certification to /sites-available/default file instead of /sites-available/calibre and the certification won't work for some reason. The solution is to get rid of all certbot certificates and then run `certbot --nginx` now it works normally for some reason. There is one more thing missing and that is that you should link the calibre file to /sites-enabled/ with `ln -s /etc/nginx/sites-available/calibre /etc/nginx/sites-enabled`.

**Comment by tfasano1** [comment]
Could you not just type `certbot` and choose the calibre domain you want to renew by number ?

**Comment by Dragallur** [comment]
> 

No. I dunno why, it might have been some problem on my part though as I said I have done the guide step by step. Anyway I think it would be just fine adding this info as a footnote and mentioning the part about having to link the sites-available and sites-enabled, also as a footnote I guess.
