### ISSUE TITLE
Fosspay Tutorial

### ISSUE THREAD

**Issue by tfasano1** [LukeSmithxyz/landchad#185]
It'd be cool to see a tutorial considering the guide on the sourcehut page is kinda [lacking](https://git.sr.ht/~sircmpwn/fosspay#installation)

**Comment by LukeSmithxyz** [comment]
Yeah I've set it up a couple times and was thinking about adding it here.

I sort of wanted to make a slimmer equivalent in Go, but there are a lot of little things to get moving together, so Fosspay might be fine. After I port over this site to Hugo I might add it.

**Comment by LukeSmithxyz** [comment]
Not sure if the developer of fosspay is even still maintaining the thing, so I don't know how good of an idea it is to add it.

Either way, there is a nearly finished draft in the new Hugo site that I might release after some doublechecks.

**Comment by LukeSmithxyz** [comment]
Added.
