### ISSUE TITLE
Backups Tutorial (Server Maintenance)

### ISSUE THREAD

**Issue by tfasano1** [LukeSmithxyz/landchad#193]
It'd be good to show how to take a "snapshot" of your vps / vm, so you could change hosting providers on a whim and not have any migration headaches. This could build upon the cronjobs guide, so you can automate backups.

I think I could figure this out on my own, but wanted to see if anyone has done this first to see the most practical method.

Also, a local backups tutorial for things like private keys and media on hardware would be nice, but might not suit this website.

**Comment by metalsp0rk** [comment]
Happy to help.  

I think there's still value in having backup strategies at least be discussed on Landchad.

**Comment by LukeSmithxyz** [comment]
I think this is a good idea and would be interested if someone added an article for this who knows it very well (I just backup things with rsync, but there might be a better way for full-system stuff).

PRs are welcome here, but I wont' be writing anything myself unless I add a section to the rsync page for my own wont.
