### ISSUE TITLE
Gitea tutorial doesn't work.

### ISSUE THREAD

**Issue by iambeingtracked** [LukeSmithxyz/landchad#199]
So, I did `curl -sL -o /etc/apt/trusted.gpg.d/morph027-gitea.asc https://packaging.gitlab.io/gitea/gpg.key` but if executing `apt update` it gives the following: `Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Get:2 https://packaging.gitlab.io/gitea gitea InRelease [2,071 B]
Hit:3 http://deb.debian.org/debian bullseye InRelease
Hit:4 http://deb.debian.org/debian bullseye-updates InRelease
Err:2 https://packaging.gitlab.io/gitea gitea InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 797DFE3F4F80269B
Reading package lists... Done
W: GPG error: https://packaging.gitlab.io/gitea gitea InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 797DFE3F4F80269B
E: The repository 'https://packaging.gitlab.io/gitea gitea InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by yoyonel** [comment]
Hello,
What os you use ? Which version ?

Here for example on docker build/run with the latest debian version i can follow the install steps:
```shell
╰─ bat Dockerfile
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: Dockerfile
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ FROM debian:latest
   2   │
   3   │ RUN apt-get update && apt-get install -y \
   4   │     curl sqlite3
   5   │
   6   │ RUN curl -sL -o /etc/apt/trusted.gpg.d/morph027-gitea.asc https://packaging.gitlab.io/gitea/gpg.key
   7   │
   8   │ RUN echo "deb [arch=amd64] https://packaging.gitlab.io/gitea gitea main" > /etc/apt/sources.list.d/morph027-gitea.list && \
   9   │     apt-get update && \
  10   │     apt-get install -y gitea
  11   │
  12   │ ENTRYPOINT ["/usr/bin/gitea", "--version"]
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
╰─ docker build -t docker.local/lukesmithxyz/gitea . && docker run docker.local/lukesmithxyz/gitea
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM debian:latest
 ---> d2780094a226
Step 2/5 : RUN apt-get update && apt-get install -y     curl sqlite3
 ---> Using cache
 ---> 17f8a485578d
Step 3/5 : RUN curl -sL -o /etc/apt/trusted.gpg.d/morph027-gitea.asc https://packaging.gitlab.io/gitea/gpg.key
 ---> Using cache
 ---> 8e0e53281e92
Step 4/5 : RUN echo "deb [arch=amd64] https://packaging.gitlab.io/gitea gitea main" > /etc/apt/sources.list.d/morph027-gitea.list &&     apt-get update &&     apt-get install -y gitea
 ---> Using cache
 ---> a3dcb0801dc0
Step 5/5 : ENTRYPOINT ["/usr/bin/gitea", "--version"]
 ---> Using cache
 ---> abc32c03e56d
Successfully built abc32c03e56d
Successfully tagged docker.local/lukesmithxyz/gitea:latest
Gitea version 1.16.8 built with GNU Make 4.1, go1.18.2 : bindata, sqlite, sqlite_unlock_notify
```

**Comment by iambeingtracked** [comment]
I am using debian 11, and not using docker, because the guide doesn't use docker.

**Comment by yoyonel** [comment]
> I am using debian 11, and not using docker, because the guide doesn't use docker.

My dockerfile and docker example was just to show you in a environment (containerize in docker) can execute the instructions in the tutorial, nothing more.
