### ISSUE TITLE
Claiming the UFW lesson

### ISSUE THREAD

**Issue by samuel-hunter** [LukeSmithxyz/landchad#20]
I've had experience writing UFW before, so I can "claim" this page to let everyone know it's being worked on, and draft a quick write-up on it.

I'm planning on three rough sections right now -- where to get it, how to use it, and maybe a few best practices how it might be used for servers.

If anyone has ideas on what I should focus on beyond that, LMK.

**Comment by nathandstevens** [comment]
I was thinking that I can write up a quick overview on IP just so that UFW can make more sense.
I think having that as a separate lesson/page would help.

Thoughts?

**Comment by samuel-hunter** [comment]
That's a good idea! The draft I have right now (#24) currently focuses less on IP addresses, but rather restricting to whatever ports you want the internet to access (and `ufw` makes it even easier since you can say "SSH" or "WWW Full" over memorizing the numbers 22 or 80,443), so while it won't be a primary prerequisite to `ufw`, it makes a good supplement.

Hmm, maybe the article should explain what exactly ports are.

**Comment by samuel-hunter** [comment]
Related PR merged
