### ISSUE TITLE
Not able to clone from the self hosted cgit frontend over http: / https:

### ISSUE THREAD

**Issue by harsh13virdi** [LukeSmithxyz/landchad#206]
I was successful in following the cgit tutorial and everything works fine. but i am unable to clone the repository that i have pushed onto my vps using the `git clone` command. any pointers would be really appreciated. 

domain name replaced with example.com

my nginx config :

[cgit.txt](https://github.com/LukeSmithxyz/landchad/files/9032625/cgit.txt)

my cgitrc:

[cgitrc.txt](https://github.com/LukeSmithxyz/landchad/files/9032627/cgitrc.txt)

**Comment by LukeSmithxyz** [comment]
I'm going to close this because it's not really an issue with cgit as I don't believe it's *supposed* to do this.

Cloning over `git://` is the canonical way, but if someone wants to add some Nginx snippet or something else that enables cloning over HTTPS, that'd be fine. I'll look it up myself in a bit.

**Comment by harsh13virdi** [comment]
https://man.archlinux.org/man/community/cgit/cgitrc.5.en

its okay if you wanna close this issue for now; but just a pointer, above is a link to arch's man page for cgitrc that lists all the available configuration. the two particular blocks i want you to give attention to is `clone-url` and `enable-http-clone` which the man page says is on by default. this is what i have been trying to get working. it could just be that i am doing it in a silly way and messing up because i have little to no expertise here. thanks again for looking into it.

**Comment by arielcostas** [comment]
> I'm going to close this because it's not really an issue with cgit as I don't believe it's _supposed_ to do this.
> 
> Cloning over `git://` is the canonical way, but if someone wants to add some Nginx snippet or something else that enables cloning over HTTPS, that'd be fine. I'll look it up myself in a bit.

I looked up how to do this, and while cloning via `git://` is the best way, providing HTTP cloning isn't really that complicated: just adding git's `git-http-backend` as a CGI script to NGINX. If you want to, I can submit a PR adding this to the guide.

**Comment by LukeSmithxyz** [comment]
Sure, you can add it as I think people will want it.

**Comment by harsh13virdi** [comment]
> > I'm going to close this because it's not really an issue with cgit as I don't believe it's _supposed_ to do this.
> > Cloning over `git://` is the canonical way, but if someone wants to add some Nginx snippet or something else that enables cloning over HTTPS, that'd be fine. I'll look it up myself in a bit.
> 
> I looked up how to do this, and while cloning via `git://` is the best way, providing HTTP cloning isn't really that complicated: just adding git's `git-http-backend` as a CGI script to NGINX. If you want to, I can submit a PR adding this to the guide.

When i try cloning over git:// the command just times out. So i thought there might be a port i needed to open on my vps. So i opened up the default port git uses (9418) and it still didn't work.

Also I found out that nginx snippet you talked about on arch wiki and i tried to make it work, changed some of the paths that were specific to arch rather than debian and still couldn't get it to work. If you wanna take a look at my nginx config i can upload it. Maybe i had made some mistake.

**Comment by harsh13virdi** [comment]
> On 16/07/2022 15:45, harsh13virdi wrote: When i try cloning over git:// the command just times out. So i thought there might be a port i needed to open on my vps. So i opened up the default port git uses (9418) and it still didn't work.
> This is probably off-topic, but you need port 9418 open, the daemon running and an empty `git-daemon-export-ok` file on the root of each repository.
> Also I found out that nginx snippet you talked about on arch wiki and i tried to make it work, changed some of the paths that were specific to arch rather than debian and still couldn't get it to work. If you wanna take a look at my nginx config i can upload it. Maybe i had made some mistake.
> Which one failed, the one on ArchWiki or the one I sent you privately? The latter was modified by me and worked on a brand-new Debian 11 server.
> […](#)
> -- Ariel

I typed that some time before exchanging e-mails with you privately, That issue was dealt with and now I am able clone from my cgit repository with no problems. Thanks again!
