### ISSUE TITLE
Blogging with latex

### ISSUE THREAD

**Issue by CarlosLoboxyz** [LukeSmithxyz/landchad#21]
Hi, a couple of months ago i discover latex and the things you can do with it, the thing is, i would like to start a personal blog using only latex to avoid Markdown since it's doesn't have math features just like .tex files.

I'm thinking about using some kind of method of compilation to generate .html files, but how can this be superior to other formats, since I'm pretty new to latex i think this is a good place to ask.

Thanks in advance :smile:

**Comment by yit6** [comment]
to make an html file from latex use the `htlatex` command

**Comment by tenseoverflow** [comment]
There probably is a need for a guide on how to use static site generators in general. If anyone's interested in making some simple guide about these, I can make one about Jekyll.
