### ISSUE TITLE
502 Bad Gateway, Following Gitea tutorial

### ISSUE THREAD

**Issue by harsh13virdi** [LukeSmithxyz/landchad#212]
After adding the repository to apt database and install Gitea. I set up the nginx proxy as guided in the tutorial. but when I accessed the configured domain on my browser to setup gitea further it just gives a 502 error. 

domain name changed with example.com

my nginx config :

[nginx.txt](https://github.com/LukeSmithxyz/landchad/files/9108373/nginx.txt)

**Comment by LukeSmithxyz** [comment]
If it's a 502, that is probably not an Nginx issue in itself, but the service Nginx is looking for isn't running or had an error. You'll have to check the Gitea logs.
