### ISSUE TITLE
Rainloop Email Server Tutorial BROKEN

### ISSUE THREAD

**Issue by TheYellowArchitect** [LukeSmithxyz/landchad#228]
https://landchad.net/mail/rainloop/#instructions
![rainloop-bugged](https://user-images.githubusercontent.com/25630803/183527999-2d0e8ab9-ffe8-441e-8d3f-f866ace1ff86.png)

I used Debian 10 in the VPS^

If this was meant for the actual computer (not the VPS), then I did try `sudo pacman -S` and the above packages, but they were outdated(?)
But I am a newbie in these things, the description doesn't even confirm which of the 2 computers the email client (rainloop) should be installed, and I wouldn't know myself if it wasn't a GUI (newbie to server administration stuff like this, could assume that you SSH to access email)

**Comment by LukeSmithxyz** [comment]
All guides are for Debian 11. I realize some pages on the site have not been updated to say this since the bump so I will be changing them.

**Comment by TheYellowArchitect** [comment]
Understandable, makes sense. But if possible, somewhere on the homepage, notify that all guides are for Debian 11, even if in small letters. ctrl+f "debian" gives no results for example. The only link of all where the OS is confirmed, is  https://landchad.net/basic/server/ (not even at the top) and a lot of users already have a VPS running. Also kinda baited me since the videos you had made were using Debian 10 for VPS

Regardless, thanks for these links, they are useful instead of watching random youtube videos cobbled together to get something running
