### ISSUE TITLE
Prosody guide missing key instructions? (firewall,nginx,port related).

### ISSUE THREAD

**Issue by Rudy-MS** [LukeSmithxyz/landchad#237]
Hello there! 

Long story short i have followed the guide several times. No matter what client I attempt to use(Pidgin or Gajim)  I cannot connect to the prosody server. 

For troubleshooting sake I have disabled the firewall on the server....I then can connect to the server successfully. 

I found a somewhat related closed issue with the guide:

https://github.com/LukeSmithxyz/landchad/issues/172

In the closed issue it is mention that Port 5222 & 5269 should be made open with UFW. 
I have also opened these ports with UFW and the clients could connect successfully.

With all that being said....is the guide broken? 

It seems to me that if the correct solution is to open the said ports in UFW then why are they not mentioned in the Prosody guide? 

Also...being a newb to all of this....the guide makes me think that there would be no need for opened ports since Nginx would handle that through ports for Nginx(80 & 443). Unless nginx does not do that sort of thing and therefore have you open the said ports? 

I hope this makes sense. Please let me know if any of you have any questions. Thank you!

**Comment by LukeSmithxyz** [comment]
Well not all guides state "you have to enable these ports" because it's usually just inferred or irrelevant for most people who don't actively install a firewall. Yeah if you run a program whose purpose is to disable some functionality, it will continue to disable that functionality.

I'm fine with someone adding it to the guide since many people are using the Vultr servers that come with ufw.

**Comment by Rudy-MS** [comment]
10/4 Thank you Luke. That would be nice if someone were to update it but not completely needed.

For others who might find this helpful, here some helpful info on what ports prosody uses:

https://prosody.im/doc/ports

I'll be opening them up on my server as needed.
