### ISSUE TITLE
Jellyfin installation guide

### ISSUE THREAD

**Issue by Eddy-Arch** [LukeSmithxyz/landchad#241]
Jellyfin is a free and open source media server (like plex).
I was wondering if you could add a section to your website as to how to set it up. (I'd be willing to write it myself).
Its a great piece of open source software and i recall you stating in one of your videos that you use kodi to stream movies,
whenever you have "normie" friends around (Jellyfin is exactly that and more)

**Comment by TheYellowArchitect** [comment]
I am certain that if you write a guide on setting up jellyfin, it will be accepted on landchad, no need to ask if you should start, especially since there is no restriction to duplicate-services (see XMPP)
