### ISSUE TITLE
Suggestion: ssg for simple static site generators

### ISSUE THREAD

**Issue by paniash** [LukeSmithxyz/landchad#29]
Hi! 

There is an article yet to be written about using a simple static site generator. I think it would be nice to use the example of [ssg](https://www.romanzolotarev.com/ssg.html) for it.

**Comment by LukeSmithxyz** [comment]
I am open to individual articles on multiple static-site generators, so if you want to start one on ssg, feel welcome.

**Comment by paniash** [comment]
Would you allow bloated static-site generators like Jekyll or _cough_... wordpress... _cough_?

**Comment by LukeSmithxyz** [comment]
WordPress is not a static site generator.

**Comment by tenseoverflow** [comment]
> Would you allow bloated static-site generators like Jekyll or _cough_... wordpress... _cough_?

If you want a CMS, a tutorial on headless CMS for integration with static site generators would be beneficial.

**Comment by wdunkelheit** [comment]
After playing around with Hugo the last few days I'm starting to realise why people like these generators so much, you can go pretty minimal with them if you really want to as well. The feature set is massive though compared to what you would need for minimal blogging static site generation. I was very impressed with it being capable of rendering an entire site faster than I can switch to my browser as well.

I would assume that it would be much simpler to reference an existing "beginner" theme from the showcased ones on the official sites for these generators. Would it be much simpler for a less experienced LandChad to just follow along that way? 

Regarding themes, I managed to convert my old html template into a theme in about an hour, so perhaps it would be worth covering converting to a static generator? 

Static site generation seems like it could be a rabbit hole of a subject to cover depending on how many of them would have tutorials.

**Comment by gitlerat** [comment]
I would be interested in the differences of ssg and https://pedantic.software/git/blogit  for example :)
