### ISSUE TITLE
Claiming: Pleroma Instance

### ISSUE THREAD

**Issue by BiasedRiot** [LukeSmithxyz/landchad#33]
Just realised after I submitted the guide that people were claiming topics so figured I'd shoot an issue here to be consistent. 
I've previously made a tutorial about it on my channel so I know some of the annoying things that trip people up during installation.

**Comment by J0hsHH** [comment]
https://youtu.be/l7mVsLSsotU
https://youtu.be/azRNReNQxUk

**Comment by LukeSmithxyz** [comment]
Now been added.
