### ISSUE TITLE
Perhaps use Caddy instead of Nginx?

### ISSUE THREAD

**Issue by phirecc** [LukeSmithxyz/landchad#43]
Caddy is another reverse proxy and web server like nginx, but which I think would make it much easier for beginners to get started. The configuration files are much more sane and beginner friendly.
So to set up a simple website this would be the contents of /etc/caddy/Caddyfile:
```
example.org {
        root * /var/www/example.org/
        file_server
}

git.example.org {
        reverse_proxy localhost:3000
}
```
Where this would automatically grab certificates for all hosts from Let's Encrypt, keep them renewed and redirect HTTP to HTTPS. For more advanced things the config for example also supports "snippets", which could be used like this:
```
(access_log) {
        log {
                output file /var/log/caddy/{args.0}/access.log
        }
}
...
        import access_log example.org
...
        import access_log git.example.org
```
If you look at their website it does look a bit soydev-y but its performance is comparable to nginx apparently. Pretty neat if you ask me.

**Comment by termermc** [comment]
While that might be the case, it will be more difficult to setup other software to work with it, since most things have guides for Nginx, but not Caddy. There are benefits with using an industry standard web server.

**Comment by Juliaria08** [comment]
> While that might be the case, it will be more difficult to setup other software to work with it, since most things have guides for Nginx, but not Caddy. There are benefits with using an industry standard web server.

Same opinion.
