### ISSUE TITLE
Maybe add a section on why people should create their own websites

### ISSUE THREAD

**Issue by JoacoAnselmo** [LukeSmithxyz/landchad#44]
In the introduction to the website there's this phrase: "Most of the internet's problems could be solved if more people had their own personal platforms, so the objective of this site is to guide any normal person through the process of installing a website.".

I think it would be helpful to also explain _which_ are these problems and _why_ any normal person should create a website, given the target audience for this website aren't technical users, much less people who are in the whole "modern internet = bad" circle.

**Comment by termermc** [comment]
Totally agree

**Comment by wdunkelheit** [comment]
Depending on the length it could end up as an article on it's own.
Perhaps cover the practical, philosophical, community building, educational, etc reasons for doing so? Everyone will have a different reason for wanting to become an internet LandChad.

I can think of a few off the top of my head:
- Censorship resistance 
   - You can post what you want (More or less)
- Become independent 
   - You no longer have to follow the rules of big tech social media
   - You can build it yourself and destroy it yourself whenever you like, no commitments.
   - Invite your friends (allow your friends to take part)
   - Your house, your rules.
- Cozy
   - Make it look however you want.
- Educational
   - Learn a little bit about how the internet works
   - Learn how to integrate your work with programs and services
   - Log your projects in a blog
- Community building
   - Make new friends (and enemies)
