### ISSUE TITLE
Certbot doesn't like TOR

### ISSUE THREAD

**Issue by Benni3D** [LukeSmithxyz/landchad#45]
I tried enabling HTTPS with Certbot, but it refused with this error message:
```
An unexpected error occurred:
The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "cujh7njfeymmh2a5q6ijeh7f5z3fpdpbsn3wfwvpo3ev3nkpp7py74id.onion": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy
```

**Comment by ElectricGeorge** [comment]
Are you trying to get a certificate for a hidden service? Unfortunately Let's Encrypt doesn't support .onion addresses. You would have to find another certificate authority (probably paid) for that. HTTPS isn't necessary for hidden services, though, as everything is encrypted and packets never exit tor.

**Comment by termermc** [comment]
Yeah, you don't need a certificate for onion sites, HTTPS is unecessary for those.

**Comment by Benni3D** [comment]
Ok thanks.

**Comment by LukeSmithxyz** [comment]
Might make a note about this in the article since I'm sure other people will also assume they need https over Tor.
