### ISSUE TITLE
Link to GitHub issues on the site, or some other place to ask questions

### ISSUE THREAD

**Issue by termermc** [LukeSmithxyz/landchad#48]
Linking to the repo's issues page would be a good avenue to allow people to add suggestions, ask questions, etc.
The repo is already linked, but not the issues page, or some other place where people can ask questions or give suggestions. Obviously people familiar with GitHub will know where to go, but it's not obvious to others.

**Comment by tenseoverflow** [comment]
I would agree. Or create a GitHub discussions page for this, since it's better meant for that stuff.

**Comment by termermc** [comment]
I didn't know it even had a discussion tab
