### ISSUE TITLE
E-Mail - Suggest Mailcow

### ISSUE THREAD

**Issue by seniorm0ment** [LukeSmithxyz/landchad#49]
E-Mail section is marked as work in progress, I presume it will be how to do everything manually. 
An alternative to manually setting up everything for the e-mail server, is Mailcow. It would be a nice addition alongside the manual setup guide.
https://mailcow.email/
It uses pretty much all the common tools, and just nicely configures everything. The most you really have to do is is setuo your dns records.
https://mailcow.github.io/mailcow-dockerized-docs/ 

I know Luke also has a script, and wants to abstain from containerization, however at least mentioning mailcow would be a good idea in my opinion.
It's just a nice alternative

**Comment by Juliaria08** [comment]
> E-Mail section is marked as work in progress, I presume it will be how to do everything manually.
> An alternative to manually setting up everything for the e-mail server, is Mailcow. It would be a nice addition alongside the manual setup guide.
> https://mailcow.email/
> It uses pretty much all the common tools, and just nicely configures everything. The most you really have to do is is setuo your dns records.
> https://mailcow.github.io/mailcow-dockerized-docs/
> 
> I know Luke also has a script, and wants to abstain from containerization, however at least mentioning mailcow would be a good idea in my opinion.
> It's just a nice alternative

For that you cloud use something like https://workaround.org/ISPMail/Buster/.

**Comment by seniorm0ment** [comment]
That actually looks pretty nice, however it's a completely different concept from Mailcow.
That guides you through and helps you understand how everything works and how to set it all up (which is excellent knowledge to have).
But it also takes significant time and if you already have a general idea, not a lot of time, Mailcow may be more of interest to someone. It's very actively maintained, and has a large community, and as I've said it essebtially does all the work for you, it could be setup in under 20min.

**Comment by Juliaria08** [comment]
That's why Luke wants to abstain from docker, because you dont know what is running on the underhood which is an issue for yourself, as Mailcow cloud easily run a crypto miner whitout you noticing, i am not saying that it is going to run it but it cloud.

**Comment by seniorm0ment** [comment]
>That's why Luke wants to abstain from docker, because you dont know what is running on the underhood which is an issue for yourself

This can literally be said about any piece of software or script and isn't really a container specific issue.
Anyways all of the software being used is completely libre, as is mailcow itself. Docker allows for excellent replicability, while I wish Mailcow also offered a non-containerized version. Everything is isolated and consistent, and are portable.
Mail can be pretty complex and for users who barely understand how to setup a website, Mailcow can make things pretty simple to be able to have their own Mail server up and running. While there are concerns about the user should really know how everything is working so they can administer it better, it is not much different than someone just installing Luke's mail script and automating the setup. 
Again, I'm not saying to use instructions to install Mailcow over a manual install or Luke's script, but I think it should at least be mentioned.
Luke's really hasn't given much for reasoning as to why he dislikes containerization, I feel he hasn't used it much, nor looked into it much, it has many practical uses, security benefits, portability benefits, and is pretty consistent across systems. While I do think all software should also offer direct host installation, I don't entirely agree with the abstaince from containerization.
Also that being said Docker does have it's issues, although Podman has been attempting to resolve those. But directly installing onto the host has it's issues as well, which is why containers have become more common. Allow the users to choose which works best for them, at least provide them with the basic knowledge that other options exist.

**Comment by phirecc** [comment]
I really liked this article, however I think Luke uses Postfix instead of OpenSMTPD
https://poolp.org/posts/2019-09-14/setting-up-a-mail-server-with-opensmtpd-dovecot-and-rspamd/

**Comment by tenseoverflow** [comment]
Mailcow requires a lot of resources to run, including ClamAV and Solr (a whopping 6gb ram **minimum**). It includes groupware features preinstalled, which might be quite a lot of bloat for just a mailserver; why not at that point setup nextcloud?

Since we're talking about newcomers owning just a tiny Vultr server with just 512mb of RAM, I don't see how running even one container on it could be possible. 

The whole website's idea was to create everything easy to even those who haven't touched a terminal in their life. They wouldn't know what containerization and Docker is and what it does, how to manage it if something goes wrong.

**Comment by Juliaria08** [comment]
> Mailcow requires a lot of resources to run, including ClamAV and Solr (a whopping 6gb ram **minimum**). It includes groupware features preinstalled, which might be quite a lot of bloat for just a mailserver; why not at that point setup nextcloud?
> 
> Since we're talking about newcomers owning just a tiny Vultr server with just 512mb of RAM, I don't see how running even one container on it could be possible.
> 
> The whole website's idea was to create everything easy to even those who haven't touched a terminal in their life. They wouldn't know what containerization and Docker is and what it does, how to manage it if something goes wrong.

True, i think you explained it better than i did.

**Comment by seniorm0ment** [comment]
>Mailcow requires a lot of resources to run, including ClamAV and Solr (a whopping 6gb ram minimum ).
ClamAV and SOLR are both optional, that's clearly stated. none the less the minimum specs they suggest are way overstated, and I and others have suggested lowering this but they don't want to.
I and many others have been running Mailcow for a long time with ClamAV and SOLR on VPS's with 2gb of ram and we usually just give it like 2-4gb of swap just in case.

>The whole website's idea was to create everything easy to even those who haven't touched a terminal in their life. They wouldn't know what containerization and Docker is and what it does, how to manage it if something goes wrong.

In what way do you feel MANUALLY setting all this up would be a easier for a newcomer than offering the users an option like Mailcow? The only reason I can see would be that they have a better understanding of what is going on under the hood, however if they can barely use a terminal, they really shouldn't be running a mail server. Either way, something like Mailcow (even if they had to learn docker basics) would be SIGNIFICANTLY simpler than manually installing all of the components, piecing them together, configuring them, then their DNS records, then also dealing with inevitable issues due to their misconfiguration, and hoping they also have done proper basic security measures. It's not that complex, but to someone who has never touched a terminal, this seems like a very poor idea imo.
And this wouldn't be any different than running a script, just instead the script will be less maintained than a project like Mailcow.

And once again, I NEVER suggested making the e-mail page only ahout Mailcow, but at least link to it within the e-mail page, would be a good idea for users who would prefer that method.
