### ISSUE TITLE
old boomer doesn't know bout directories

### ISSUE THREAD

**Issue by iamlambda** [LukeSmithxyz/landchad#5]
he says he keeps his ~ clean but doesn't create folders to clean his repos

**Comment by zacharytyhacz** [comment]
I do agree that isolating guides into their own folders would be pretty nice and organized.

Maybe something like this:

```
index.html

bitcoin/
         - index.html
         - someGuideRelatedImage.png

dns-setup/
        - index.html
        - dnsReferenceGoDaddy.png

setup-rss-feed/
         - index.html

nginx-webserver/
         - index.html


otherNewGuide/
          index.html

```

and all urls/links can be absolute paths so everything works
