### ISSUE TITLE
Suggestion: Using Namecoin for decentralized DNS

### ISSUE THREAD

**Issue by yanmaani** [LukeSmithxyz/landchad#52]
I have a suggestion for a topic.

Namecoin is basically Bitcoin but applied to domain names. Names are stored on the blockchain, and the same rules that ensure you can't spend other people's money ensure you can't register names that are already taken.

Namecoin can be used in for ZeroNet zites ([ZeroName plugin, included in standard ZeroNet](https://github.com/HelloZeroNet/ZeroName/)), with Tor Browser in official nightly builds for .onion sites (see https://www.namecoin.org/resources/presentations/36C3/tor-workshop/ for instructions), and with ncdns (system-wide) for normal clearnet websites. (It is also theoretically possible to use for other services, like I2P and Freenet, but the client-side hasn't been implemented.) Using Namecoin does not require a full download of the blockchain. It costs NMC 0.01 (about $0.013 at current exchange rates) to register a Namecoin name.

Using Namecoin takes away the reliance on centralized DNS services, which is the last piece in the puzzle of decentralization. Namecoin can also be used [for SSL](https://www.namecoin.org/docs/name-owners/tls/), to trustlessly replace centralized certificate authorities. Domains need to be renewed every ~8 months, but nothing has to actively run on the server for them to resolve - the keys can be kept entirely in cold storage if needed.

Would a guide for this, seeing as it's a bit of a niche technology, be within scope?

I am willing to write the actual article. (Disclaimer: I am a contributor to Namecoin. I do not have any direct financial incentive in its success or its price going up.)

**Comment by LukeSmithxyz** [comment]
I'm not really familiar with the technology, but if you write an article on it, I will certainly consider adding it since it sounds very relevant.
