### ISSUE TITLE
Nextcloud Setup Problems

### ISSUE THREAD

**Issue by Daxiel1992** [LukeSmithxyz/landchad#59]
Following along with the Nextcloud tutorial and I just finished setting everything up except nginx fails to reload or restart.

`nginx[4099]: nginx: [emerg] unknown directive "pagespeed" in /etc/nginx/sites-enabled/nextcloud:49`

Couldn't find any answers online so I just commented the line out in curiosity and then got another error this time for a php-handler. I made sure to install all the proper packages and I enabled and made sure all the right services are running, but I'm afraid I don't have enough experience with this and am in need of assistance. Thank you!

**Comment by Daxiel1992** [comment]
Okay I found the Nextcloud documentation and that helped piece everything together. Firstly, pagespeed isn't needed if you haven't built nginx with it, and if you are following along with the website, you haven't either. So we can just comment that out. Next, I needed to add 
`upstream php-handler {
    server 127.0.0.1:9000;
    #server unix:/var/run/php/php7.4-fpm.sock;
}`
Lastly, the ssl certificate path given on the website is not the default path for certbot and I got that fixed too.

**Comment by Daxiel1992** [comment]
The only issue now is I am getting a 404 error despite everything else working fine -_-

**Comment by Daxiel1992** [comment]
Everything works now. On the upstream php-handler block, I just needed to use the sock server instead of the home address... The Nextcloud page needs some rewrites to help avoid this confusion, though a lot of it is still on me.

**Comment by phirecc** [comment]
@MattMadness

**Comment by LukeSmithxyz** [comment]
Yeah the Nextcloud article is the one article up that I have not validated myself. This needs to be fixed.
