### ISSUE TITLE
Github actions for automatic website deployment

### ISSUE THREAD

**Issue by din14970** [LukeSmithxyz/landchad#6]
Crowd sourced knowledge about these topics and throwing it into a simple site is a cool idea, thanks for making the project. I actually started my own little blog/personal site thanks to your videos. 

This is just a suggestion and may be too soydevy for your taste, but you could implement a Github action that automatically uploads your site to the server whenever you push to/merge with the master branch. It would help you keep the site automatically up to date with the latest "stable" version on Github. I detail how I did it for my static site [here](https://nielscautaerts.xyz/deploying-a-pelican-static-site-with-github-actions.html). It's not perfect but perhaps if you are not totally opposed to the idea you could adapt some ideas from it.

**Comment by LukeSmithxyz** [comment]
I do this for based.cooking, but I'm not sure if it will be as necessary here since I don't even plan to use a static site generator. based.cooking is recompiled on the web server each push. Maybe though depending on how things evolve I will do something like that here.
