### ISSUE TITLE
Specify $ or # Before Commands

### ISSUE THREAD

**Issue by seniorm0ment** [LukeSmithxyz/landchad#67]
Suggesting adding $ or # before commands to clairfy how the command should be run (user/root). This is fairly common practice when websites list commands.

**Comment by wdunkelheit** [comment]
Whether a command is being run by a user or by root should be obvious from the context however it may not be clear in some cases.

**Comment by seniorm0ment** [comment]
Commands can often be run in user or root, however it may mess up things, or be of concern from a security pov if ran as root when it shouldn't be or doesn't need to be.
Not to mention the point of the site being to target people with less experience, as a reference. Imo this is pretty straightforward I fail to see why we wouldn't want to add these.
