### ISSUE TITLE
Consider recommending Caddy rather than nginx+certbot

### ISSUE THREAD

**Issue by francislavoie** [LukeSmithxyz/landchad#72]
You can replace sections 4 and 5 with just one by recommending Caddy.

https://caddyserver.com/

Much simpler config, best-in-class ACME client implementation built into the web server. Tons of other features.

The config would just become:

```
landchad.net {
	root * /var/www/landchad
	file_server
}
```

And this gets you automated TLS certificates out of the box.

**Comment by phirecc** [comment]
#43

**Comment by francislavoie** [comment]
Don't knock it til you try it etc, but okay
