### ISSUE TITLE
[ Suggestion ] file hierarchy

### ISSUE THREAD

**Issue by chadholes** [LukeSmithxyz/landchad#73]
Except for style and image files, other HTML files can be grouped under `pages/`

for example:

.
├── pix
├── pages
│   ├── git.html
│   └── foo-bar.html
└── ...

**Comment by wdunkelheit** [comment]
All of the documents would need to update their references to reference from root.
Instead of:
```html
<link rel='stylesheet' type='text/css' href='style.css'>
```
They would need:
```html
<link rel='stylesheet' type='text/css' href='style.css'>
```
Similar edits would be required for images as they reference the pix folder from their current directory.

**Comment by LukeSmithxyz** [comment]
What would be the purpose of doing that?
