### ISSUE TITLE
Extending SSH page

### ISSUE THREAD

**Issue by artur-borys** [LukeSmithxyz/landchad#74]
Hello,
I think some people might find it useful to use a config file for ssh client. You can store specific settings for each host in there - like using a different key for each host or using a custom port without having to always specify it when issuing a ssh command.

I also think there could be an information about SSH tunneling.

I can work on it in my spare time, but I'm not sure if I should refactor "Use your SSH keys to prevent hacking" to a general page about SSH or create a separate page for it?

**Comment by wdunkelheit** [comment]
Maybe an `Advanced SSH Usage` page that takes into context that the user's only experience with SSH so far is the other related articles on the site would work?

**Comment by artur-borys** [comment]
> Maybe an `Advanced SSH Usage` page that takes into context that the user's only experience with SSH so far is the other related articles on the site would work?

Yeah, that's a good idea. I have already started working on this in my forked repo.
