### ISSUE TITLE
Suggestion: Python/Flask backend tutorial

### ISSUE THREAD

**Issue by maxgravitte** [LukeSmithxyz/landchad#8]
I have experience writing simple Flask apps with SQLite or SQLAlchemy databases. I am currently writing articles for my own site that cover Python, handling HTTP requests, and databases. In my opinion these tools are the most straight-forward way of creating web applications for more advanced sites. Do any of these topics sound useful for this webpage?

**Comment by LukeSmithxyz** [comment]
I'd say I'm open to this in the future, but I'd like to have most of the stuff I have listed out there written first.

I want to make sure there is a foundation of simple/"amaturish"/DIY stuff about hosting your own services before moving on to the kind of software more likely to be used for professional development. That said, if there is some highly useful flask application that might go to this end, I might consider it sooner.
