### ISSUE TITLE
XMPP: E2E encryption section not needed

### ISSUE THREAD

**Issue by ALakeInTexas** [LukeSmithxyz/landchad#85]
The functionality of `omemo_all_access` is provided by `pep` by default on in prosody version 11 and higher. This is the version users are going to have installed if they have followed the other tutorials on the website. Maybe a note that you can ignore that section if you're running version 11 or higher would be good

**Comment by LukeSmithxyz** [comment]
Ah, that's my error then. I'll remove the section in a bit then.
