### ISSUE TITLE
Can't restart nginx

### ISSUE THREAD

**Issue by thomasok04** [LukeSmithxyz/landchad#89]
G'day everyone, having the following issue when trying to reload nginx: 

"nginx: [emerg] BIO_new_file("/etc/ssl/nginx/yourwebsite.com.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/nginx/yourwebsite.com.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)"

This occurs after installing SSL on my server.

Any help would be appreciated.

Tom

**Comment by phirecc** [comment]
The error message is pretty self-explanatory, it is trying to load a file which doesn't exist.
Replace every instance of `yourwebsite.com` with your actual domain in `/etc/nginx/nginx.conf`. If you `ls /etc/ssl/nginx` you should see files for your domain if you used certbot correctly.

**Comment by thomasok04** [comment]
> The error message is pretty self-explanatory, it is trying to load a file which doesn't exist.
> Replace every instance of `yourwebsite.com` with your actual domain in `/etc/nginx/nginx.conf`. If you `ls /etc/ssl/nginx` you should see files for your domain if you used certbot correctly.

Hey Phirecc,

Cheers for the response, I've looked through `/etc/nginx/nginx.conf` and `yourwebsite.com` doesn't appear anywhere. I've also looked through `/etc/ssl/nginx` and I can see `README	cert.pem  chain.pem  fullchain.pem  privkey.pem`, which to the best of my knowledge is what should be there. Anything else?

**Comment by phirecc** [comment]
The nextcloud guide uses `/etc/nginx/sites-available/`, so check there. Somewhere in your nginx config you're telling it to load that certificate.
