### ISSUE TITLE
Wireguard VPN guide

### ISSUE THREAD

**Issue by artur-borys** [LukeSmithxyz/landchad#92]
I could write a guide about setting up Wireguard VPN (https://www.wireguard.com/).
During the last weekend I've managed to set it up on my VPS, with two variants of routing - only to the VPN subnet or passing the whole traffic via the VPN tunnel.

It's much lighter than OpenVPN.

However, since the topic isn't listed in the "on the lookout for" section, I don't want to spend time on writing the guide if the potential PR will be ignored like my previous one (#75)

**Comment by termermc** [comment]
I like WireGuard and use it myself, but it's overly complicated and most people won't get much use out of it I think.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by phirecc** [comment]
How is wireguard complicated? It's much simpler than anything else out there

**Comment by termermc** [comment]
The system is simple, setup is not. You have to generate keys for each computer, and manually add them. There is no easy to use GUI client, and setup is not quick compared to things like OpenVPN. This isn't me shitting on it, it's just a matter of fact.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by artur-borys** [comment]
Well, if I'm up to date with OpenVPN, it requires much more steps on the server side, than Wireguard. Wireguard has wg-quick, which allows you to write config files instead of using commands. The only thing you still have to do is generate the keys, but that's something that can be easily done with bash script. I have also planned to create a single script or a set of scripts that will make it easier to manage wireguard server-side. And on the client side - Windows has a GUI, Android has a GUI, many gui network managers on linux can read wg-quick config files or allow to define a profile for wireguard connection.

PS. I know wireguard doesn't have to have a single server, but I think it's the most useful guide for landchad - to allow yourself and you friends to securely access internet on public wifi, share a network etc. especially because of the fact, that most people are behind NAT and don't have a public IP to create a P2P wireguard network

**Comment by phirecc** [comment]
Agree with the above, OpenVPN is very complex for what it is and personally I've never bothered to set a server up manually in the past, I always just used some multiple-thousand loc bash script I found somewhere on the internet. Meanwhile wireguard is simple by design, just werks and can be grasped in its entirety in an hour.

**Comment by TheYellowArchitect** [comment]
There is a gemini and jitsi article, both of which won't have many users putting them on their server, yet there will be some users benefitting of them for sure. I have used openvpn in the past, its garbage imo, and while the use-case is rare, I see myself using openvpn/wireguard more likely than gemini/jitsi, so I guess give it a try if you think it's better than openvpn

**Comment by termermc** [comment]
I guess so

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
