### ISSUE TITLE
Suggestion: Tutorial for Jitsi meet/BigBlueButton (Zoom/MS Teams/Skype libre replacements)

### ISSUE THREAD

**Issue by emmanuelroque** [LukeSmithxyz/landchad#94]
Due to the pandemic, many activities are currently held online. In particular, academic activities for schools of different levels all around the world. Many schools and universities are using proprietary Web conference solutions. There are free-libre replacements that need to be setup using a server such as Jitsi meet and BigBlueButton. 

With a beginner friendly tutorial, some teachers and other event organizers might be willing to drop their usage of Zoom/MS Teams and go for a libre and privacy respecting solution.

**Comment by LukeSmithxyz** [comment]
Yes. Good idea. Jitsi I know is pretty simple to set up and also easy to interface with XMPP and Matrix. I haven't used it myself that much, so I will give it some time if someone else more familiar wants to write an article, but otherwise I will make one myself eventually.

**Comment by J053Fabi0** [comment]
I can create the article.

**Comment by J053Fabi0** [comment]
Done 👍🏻 #102

**Comment by LukeSmithxyz** [comment]
Added.
