### ISSUE TITLE
Build your wall

### ISSUE THREAD

**Issue by Yanpas** [LukeSmithxyz/landchad#96]
That may be a bit outside of landchad idea, but I guess a lot of people don't care that much about sharing their stuff to the outside and want their personal safe space with their private nextcloud, photos (librephotos) and stuff like that. At least some stuff they want to be private (I personally don't trust php-written nexcloud in terms of security). Leaving open every TCP port from gitea to nextcloud is like keeping a safe outside of a house.

What comes to my mind on building your intranet:
- a guide on how to setup some private server at your house (what specs to pay attention when you buy it if any, making some ports visible behind NAT).
- making your "services" or part of them accessible only when you are connected to your private network (VPN or tunnel to your home local) . Some TCP/IP theory might be required.
- log monitoring software, sending emails on ssh access, ssh key authorization and other security tips.

**Comment by termermc** [comment]
Could be in an extras section

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by phirecc** [comment]
Something about general security practices might be nice too. Systemd has some basic sandboxing functionality similar to SELinux and every service should run under separate, non-root users. I find it strange that the systemd service files shipped by debian don't include good service configs with sandboxing while the ones from arch do.
